services:
  gateway:
    build:  
      context: ./
    command: 
      - "lc500"
      - "gateway"
      - "serve"
    depends_on:
      - minio
      - worker
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      WORKER_TARGET: worker:8080
      WORKER_INSECURE: "true"
      BLUEPRINT_TARGET: blueprint:8082
      AWS_ENDPOINT: http://minio:9000
      AWS_REGION: ap-northeast-1
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_BUCKET: tenant-scripts
  worker:
    build:
      context: ./
    command:
      - "lc500"
      - "worker"
      - "serve"
      - "--port"
      - "8080"
  minio:
  # 別名をつけて別のホスト名でもアクセスさせたい
    networks:
      default:
        aliases:
          - tenant-scripts.minio

    image: minio/minio
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - minio_data:/export
      - minio_config:/root/.minio
    environment:
      MINIO_BUCKET: 
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DOMAIN: minio
    command: server /export --console-address ":9001"
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/tenant-scripts;
      /usr/bin/mc policy download myminio/tenant-scripts;
      exit 0;
      "
  blueprint:
    image: golang:1.23
    volumes:
      - "./blueprint:/app"
    command:
      - "go"
      - "run"
      - "/app/main.go"
    environment:
      PORT: 8082
      DATABASE_PATH: /app/database.json

volumes:
  minio_data:
  minio_config:
